# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_fsrsr_wrappers", use_symbols = TRUE, package_name = "fsrsr")

#' @usage NULL
#' @useDynLib fsrsr, .registration = TRUE
NULL

#' Get default FSRS parameters
#' @export
fsrs_default_parameters <- function() .Call(wrap__fsrs_default_parameters)

#' Calculate next interval
#' @param stability Current stability
#' @param desired_retention Target retention (0.0-1.0)
#' @export
fsrs_next_interval <- function(stability, desired_retention) .Call(wrap__fsrs_next_interval, stability, desired_retention)

#' Initial memory state for new card
#' @param rating Rating: 1=Again, 2=Hard, 3=Good, 4=Easy
#' @export
fsrs_initial_state <- function(rating) .Call(wrap__fsrs_initial_state, rating)

#' Next memory state after review
#' @param stability Current stability
#' @param difficulty Current difficulty  
#' @param elapsed_days Days since last review
#' @param rating Rating: 1=Again, 2=Hard, 3=Good, 4=Easy
#' @export
fsrs_next_state <- function(stability, difficulty, elapsed_days, rating) .Call(wrap__fsrs_next_state, stability, difficulty, elapsed_days, rating)

#' Calculate retrievability (recall probability)
#' @param stability Card stability
#' @param elapsed_days Days since last review
#' @export
fsrs_retrievability <- function(stability, elapsed_days) .Call(wrap__fsrs_retrievability, stability, elapsed_days)


# nolint end
